-- Sample data for categories
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Tecnología', 'Discusiones sobre tecnología y gadgets.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Deportes', 'Conversaciones sobre deportes y eventos deportivos.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Cine', 'Reseñas y discusiones sobre películas y series.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Música', 'Discusiones sobre música y artistas.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Cocina', 'Recetas y consejos de cocina.');

-- Sample data for threads
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Nuevos smartphones 2025', SYSDATE, SYSDATE, 1, 1);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Final de la Copa del Mundo', SYSDATE, SYSDATE, 2, 2);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Películas recomendadas', SYSDATE, SYSDATE, 3, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Conciertos próximos', SYSDATE, SYSDATE, 4, 4);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Recetas de postres', SYSDATE, SYSDATE, 5, 5);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Tecnología en el hogar', SYSDATE, SYSDATE, 6, 1);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Deportes extremos', SYSDATE, SYSDATE, 7, 2);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Series de TV', SYSDATE, SYSDATE, 8, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Música clásica', SYSDATE, SYSDATE, 9, 4);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Cocina internacional', SYSDATE, SYSDATE, 10, 5);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Gadgets del futuro', SYSDATE, SYSDATE, 11, 1);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Deportes de invierno', SYSDATE, SYSDATE, 12, 2);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Películas de terror', SYSDATE, SYSDATE, 13, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Conciertos de rock', SYSDATE, SYSDATE, 14, 4);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) VALUES (THREAD_SEQ.NEXTVAL, 'Recetas vegetarianas', SYSDATE, SYSDATE, 15, 5);

-- Sample data for posts
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) VALUES (POST_SEQ.NEXTVAL, 'El nuevo iPhone 15 es increíble.', SYSDATE, SYSDATE, 1, 1);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) VALUES (POST_SEQ.NEXTVAL, 'La final fue emocionante.', SYSDATE, SYSDATE, 2, 2);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) VALUES (POST_SEQ.NEXTVAL, 'Recomiendo ver Inception.', SYSDATE, SYSDATE, 3, 3);
